import UIKit
import XCTest

@testable import Minis

/// [sting-1 / GAP-REVIEW IMG-1/2/3/4] Regression tests for the unified
/// image preparation (ImagePayloadPrep) and its message-level transforms:
/// magic-byte labelling, the pass-through rules, the self-heal message
/// transforms, and the vision-capability gate.
final class ImagePayloadPrepTests: XCTestCase {

    // MARK: - sniffMimeType

    func testSniff_jpeg_magic() {
        XCTAssertEqual(ImagePayloadPrep.sniffMimeType(Data([0xFF, 0xD8, 0xFF, 0xE0])), "image/jpeg")
    }

    func testSniff_png_magic() {
        let d = Data([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A])
        XCTAssertEqual(ImagePayloadPrep.sniffMimeType(d), "image/png")
    }

    func testSniff_gif_magic() {
        XCTAssertEqual(ImagePayloadPrep.sniffMimeType(Data([0x47, 0x49, 0x46, 0x38, 0x39, 0x61])), "image/gif")
    }

    func testSniff_webp_magic() {
        let riff = Data([0x52, 0x49, 0x46, 0x46, 0x00, 0x00, 0x00, 0x00, 0x57, 0x45, 0x42, 0x50])
        XCTAssertEqual(ImagePayloadPrep.sniffMimeType(riff), "image/webp")
    }

    func testSniff_heic_ftypBrand() {
        // ftyp box with heic brand
        let d = Data([0x00, 0x00, 0x00, 0x18, 0x66, 0x74, 0x79, 0x70, 0x68, 0x65, 0x69, 0x63])
        XCTAssertEqual(ImagePayloadPrep.sniffMimeType(d), "image/heic")
    }

    func testSniff_tiff_bmp_andUnknown() {
        XCTAssertEqual(ImagePayloadPrep.sniffMimeType(Data([0x49, 0x49, 0x2A, 0x00])), "image/tiff")
        XCTAssertEqual(ImagePayloadPrep.sniffMimeType(Data([0x42, 0x4D, 0x36])), "image/bmp")
        XCTAssertNil(ImagePayloadPrep.sniffMimeType(Data([0x00, 0x01, 0x02, 0x03])))
        XCTAssertNil(ImagePayloadPrep.sniffMimeType(Data([0xFF])))
    }

    // MARK: - preparedForContext

    /// Build a solid-colour image of the given size in the given format.
    private func imageData(width: Int, height: Int, format: String) -> Data {
        let size = CGSize(width: width, height: height)
        let renderer = UIGraphicsImageRenderer(size: size)
        let img = renderer.image { ctx in
            UIColor.red.setFill()
            ctx.fill(CGRect(origin: .zero, size: size))
        }
        switch format {
        case "png":
            return img.pngData()!
        case "jpeg":
            return img.jpegData(compressionQuality: 0.9)!
        default:
            fatalError("unsupported test format")
        }
    }

    func testPrepared_smallPng_passesThroughUntouched() {
        let png = imageData(width: 100, height: 100, format: "png")
        let out = ImagePayloadPrep.preparedForContext(png)
        XCTAssertNotNil(out)
        // Label must come from the bytes: PNG stays PNG with IDENTICAL bytes.
        XCTAssertEqual(out?.mimeType, "image/png")
        XCTAssertEqual(out?.data, png)
    }

    func testPrepared_smallJpeg_passesThroughUntouched() {
        let jpeg = imageData(width: 100, height: 100, format: "jpeg")
        let out = ImagePayloadPrep.preparedForContext(jpeg)
        XCTAssertEqual(out?.mimeType, "image/jpeg")
        XCTAssertEqual(out?.data, jpeg)
    }

    func testPrepared_oversizePng_reencodedToJpegUnder1536() {
        let big = imageData(width: 2000, height: 1500, format: "png")
        let out = ImagePayloadPrep.preparedForContext(big)
        XCTAssertNotNil(out)
        // 2000px long edge exceeds the 1536 cap → re-encoded, and the
        // re-encode is genuinely JPEG (label matches bytes).
        XCTAssertEqual(out?.mimeType, "image/jpeg")
        XCTAssertEqual(ImagePayloadPrep.sniffMimeType(out!.data), "image/jpeg")
        let size = ImagePayloadPrep.pixelSize(out!.data)!
        XCTAssertLessThanOrEqual(max(size.width, size.height), 1536)
    }

    func testPrepared_undecodable_returnsNil() {
        XCTAssertNil(ImagePayloadPrep.preparedForContext(Data([0x00, 0x01, 0x02, 0x03, 0x04])))
        XCTAssertNil(ImagePayloadPrep.preparedForContext(Data()))
    }

    func testPrepared_cannotFitBudget_returnsNil() {
        // A 100×100 image forced through a 10-byte budget can never fit.
        let jpeg = imageData(width: 100, height: 100, format: "jpeg")
        XCTAssertNil(ImagePayloadPrep.preparedForContext(jpeg, maxBytes: 10))
    }

    func testPrepared_heicNotInStandardSet_convertsToJpeg() {
        // Can't synthesize HEIC on a simulator; drive the conversion branch
        // with a TIFF magic prefix — TIFF is not in the standard passthrough
        // set, so the payload must come back re-encoded as labelled JPEG.
        // (solid TIFF bytes can't be generated by UIKit; skip actual TIFF
        //  decode and rely on the undecodable→nil contract instead.)
        // This test pins the contract indirectly: an unreadable "exotic"
        // payload must NOT go out with a guessed label.
        XCTAssertNil(ImagePayloadPrep.preparedForContext(Data([0x49, 0x49, 0x2A, 0x00, 0x99, 0x88])))
    }

    // MARK: - Message transforms

    private func messageWithImage(path: String? = "/var/minis/attachments/uploads/a.png") -> AgentMessage {
        AgentMessage(role: .user, parts: [
            .text("look"),
            .imageData(data: Data([0xFF, 0xD8, 0xFF]), mimeType: "image/png", linuxPath: path),
            .toolResult(id: "t1", name: "shot", content: "ok", isError: false,
                        imageData: Data([0xFF, 0xD8, 0xFF]), imageMimeType: "image/png",
                        pageURL: nil, imageLinuxPath: path),
        ])
    }

    func testGate_visionCapable_unchanged() {
        let msgs = [messageWithImage()]
        let gated = AgentMessage.gatedForVisionCapability(msgs, supportsImageInput: true)
        // No copy when nothing changes.
        XCTAssertEqual(gated.count, 1)
        XCTAssertTrue(AgentMessage.containsImagePayload(gated))
    }

    func testGate_textOnly_replacesImagesWithPlaceholder() {
        let gated = AgentMessage.gatedForVisionCapability([messageWithImage()], supportsImageInput: false)
        XCTAssertEqual(gated.count, 1)
        XCTAssertFalse(AgentMessage.containsImagePayload(gated))
        // Attachment image becomes the shared OpenAI-style placeholder text.
        let texts = gated[0].parts.compactMap { part -> String? in
            if case .text(let t) = part { return t }
            return nil
        }
        XCTAssertTrue(texts.contains { $0.contains("does not support") })
        // Tool result keeps its text content with the image dropped.
        let toolResults: [AgentContentPart] = gated[0].parts.filter {
            if case .toolResult = $0 { return true }
            return false
        }
        XCTAssertEqual(toolResults.count, 1)
        if case .toolResult(_, _, let content, _, let imageData, _, _, _) = toolResults[0] {
            XCTAssertEqual(content, "ok")
            XCTAssertNil(imageData)
        } else {
            XCTFail("expected toolResult part")
        }
    }

    func testStrip_replacesAllImagePayloads_keepingPath() {
        let stripped = AgentMessage.replacingImagesWithPlaceholders([messageWithImage()])
        XCTAssertFalse(AgentMessage.containsImagePayload(stripped))
        let texts = stripped[0].parts.compactMap { part -> String? in
            if case .text(let t) = part { return t }
            return nil
        }
        XCTAssertTrue(texts.contains { $0.contains("/var/minis/attachments/uploads/a.png") })
    }

    func testStrip_noPath_stillPlaceholder() {
        let stripped = AgentMessage.replacingImagesWithPlaceholders([messageWithImage(path: nil)])
        XCTAssertFalse(AgentMessage.containsImagePayload(stripped))
    }

    func testContainsImagePayload_negative() {
        let msgs = [AgentMessage(role: .user, parts: [.text("hello")])]
        XCTAssertFalse(AgentMessage.containsImagePayload(msgs))
    }

    // MARK: - errorImplicatesImagePayload

    func testErrorImplicatesImage_imageErrors() {
        XCTAssertTrue(AIChatViewModel.errorImplicatesImagePayload(
            LLMError.providerError(message: "Invalid image: image exceeds 5 MB maximum")))
        XCTAssertTrue(AIChatViewModel.errorImplicatesImagePayload(
            LLMError.providerError(message: "Could not process image")))
        XCTAssertTrue(AIChatViewModel.errorImplicatesImagePayload(
            LLMError.providerError(message: "Downloaded image content cannot exceed 30MB")))
        XCTAssertTrue(AIChatViewModel.errorImplicatesImagePayload(
            LLMError.providerError(message: "HTTP 413: request entity too large")))
        XCTAssertTrue(AIChatViewModel.errorImplicatesImagePayload(
            LLMError.providerError(message: "media_type does not match data")))
    }

    func testErrorImplicatesImage_nonImageErrors() {
        XCTAssertFalse(AIChatViewModel.errorImplicatesImagePayload(
            LLMError.providerError(message: "Internal server error")))
        XCTAssertFalse(AIChatViewModel.errorImplicatesImagePayload(
            LLMError.rateLimited()))
        XCTAssertFalse(AIChatViewModel.errorImplicatesImagePayload(
            LLMError.invalidAPIKey))
    }
}
